<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="DESKTOP-7PFC2E7" name="Appium.Assignment.AddProductToCart" tests="4" failures="1" timestamp="2020-09-20T16:00:11 IST" time="112.677" errors="0">
  <testcase name="SelectRandomProductTest" time="14.889" classname="Appium.Assignment.AddProductToCart"/>
  <system-out>
SelectRandomProductTest has started product name is Mi TV 4X 163.9 cm (65 Inches) 4K Ultra HD Android LED TV (Black) product price is 64999 Clicked on a random product SelectRandomProductTest has PASSED  </system-out>
  <testcase name="SearchProductTest" time="19.757" classname="Appium.Assignment.AddProductToCart"/>
  <system-out>
SearchProductTest has started Inside SearchProductTest SearchProductTest has PASSED  </system-out>
  <testcase name="AddProductToCartTest" time="78.031" classname="Appium.Assignment.AddProductToCart">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at Appium.Assignment.AddProductToCart.AddProductToCartTest(AddProductToCart.java:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- AddProductToCartTest -->
  <system-out>
AddProductToCartTest has started AddProductToCartTest has FAILED  </system-out>
  <testcase name="ValidateProductDetailsTest" time="0.000" classname="Appium.Assignment.AddProductToCart">
    <skipped/>
  </testcase> <!-- ValidateProductDetailsTest -->
  <system-out>
ValidateProductDetailsTest has been SKIPPED  </system-out>
</testsuite> <!-- Appium.Assignment.AddProductToCart -->
